package model;

import model.base.BaseRechargemmoney;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Rechargemmoney extends BaseRechargemmoney<Rechargemmoney> {
	public static final Rechargemmoney dao = new Rechargemmoney().dao();
}
