package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRecord<M extends BaseRecord<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCustomerId(java.lang.Integer customerId) {
		set("customerId", customerId);
		return (M)this;
	}
	
	public java.lang.Integer getCustomerId() {
		return getInt("customerId");
	}

	public M setHairdressingTypeId(java.lang.Integer hairdressingTypeId) {
		set("hairdressingTypeId", hairdressingTypeId);
		return (M)this;
	}
	
	public java.lang.Integer getHairdressingTypeId() {
		return getInt("hairdressingTypeId");
	}

	public M setStaffId(java.lang.Integer staffId) {
		set("staffId", staffId);
		return (M)this;
	}
	
	public java.lang.Integer getStaffId() {
		return getInt("staffId");
	}

	public M setDate(java.lang.String date) {
		set("date", date);
		return (M)this;
	}
	
	public java.lang.String getDate() {
		return getStr("date");
	}

}
