package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRecharge<M extends BaseRecharge<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCustomerId(java.lang.Integer customerId) {
		set("customerId", customerId);
		return (M)this;
	}
	
	public java.lang.Integer getCustomerId() {
		return getInt("customerId");
	}

	public M setAmountMoney(java.lang.Integer amountMoney) {
		set("amountMoney", amountMoney);
		return (M)this;
	}
	
	public java.lang.Integer getAmountMoney() {
		return getInt("amountMoney");
	}

}
